[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
to_do_dapp = "4Q9JYPxgUk8VTuStU6FDh7U3Xw78j9cfX8z2Qt9SYntK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/akshay/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
